module.exports = {
    // WILL BE POPUULATED FROM TWITTER APP PAGE
    TWITTER_KEY : 'JkSZCughN5L40yqDr3DJIYr5F',
    TWITTER_SECRET: '2WaA2gM0xX34Rw2jNhuIxpreHk5TiGDotWI1F704nlmkaU2ATA',
    TWITTER_CALLBACK: 'http://localhost:8000'
}